name: LinuxDo签到【Anya】
on:
  schedule:
    - cron: "55 00 * * *"
  workflow_dispatch:

env:
  # time zone
  TZ: Asia/Shanghai

jobs:
  aggregate:
    runs-on: ubuntu-latest
    name: Checkin for https://linux.do

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Sync
        run: |
          git submodule init
          git submodule update --remote

          # sync linuxdo
          cd ./linuxdo

          git checkout main
          git pull -f origin main

          cd ..

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Checkin
        env:
          # username
          LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME_ANYA }}

          # password
          LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD_ANYA }}

          # like probability
          LIKE_PROBABILITY: ${{ vars.LINUXDO_LIKE_PROBABILITY }}

          # auto reply probability
          REPLY_PROBABILITY: ${{ vars.LINUXDO_REPLY_PROBABILITY }}

          # mark probability
          COLLECT_PROBABILITY: ${{ vars.LINUXDO_COLLECT_PROBABILITY }}
        run: |
          pip3 install playwright requests tabulate configparser
          playwright install
          python -u ./linuxdo/main.py

        if: ${{ vars.LINUXDO_KEEP_ALIVE_ANYA != 'false' }}