name: NodeSeek签到

on:
  schedule:
    - cron: '00 01 * * *'
    - cron: '45 08 * * *'
  workflow_dispatch:

jobs:
  nodeseek-checkin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: "x64"

      - name: Install Chrome
        working-directory: ./nodeseek
        run: |
          # 安装依赖
          sudo apt-get update
          sudo apt-get install -y wget gnupg xvfb
          
          # 添加 Google Chrome 官方源
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          
          # 安装稳定版 Chrome
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          echo "Chrome version:"
          google-chrome --version

      - name: Install Dependencies
        working-directory: ./nodeseek
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-wqy-zenhei
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Checkin
        working-directory: ./nodeseek
        env:
          NS_COOKIE: ${{ secrets.NODESEEK_COOKIE }}
          NS_RANDOM: ${{ vars.NODESEEK_RANDOM }}
          NS_COMMENT: ${{ vars.NS_COMMENT }}
          NS_COMMENT_URL: ${{ vars.NS_COMMENT_URL }}
          NS_DELAY_MIN: ${{ vars.NS_DELAY_MIN }}
          NS_DELAY_MAX: ${{ vars.NS_DELAY_MAX }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          HEADLESS: "false"
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python nodeseek_daily.py

